Merge branches, test and note some initial comments. Das 3D view mit plane-slider am rechts sieght uber-schoen aus!
- drawing in 'erase mode' first displays label color, but seems to get erased after 's' ... mostly

- extremely annoying for D(\phi,\phi^*) to grow outside the visible domain

- using "-c 20" makes it ~5x faster feeling than default 100 arg

- note: regular chan-vese is nice in some sense for large bright blobs, but
it is bad in that there are very few stable minima. This promotes growing the curve
into bad regions where local-global would have found a local min and stopped.

- save and load labels works

- Fails and almost certainly much easier for Karl to fix: load labels once. Rotate
the view. Now save again. Exit and reload labels. They are mis-aligned with respect
to image now. On re-load either the image needs to rotate, or the labels need to map
back to identity.

- MRI data segfault on pressing 's'; noticed the following log at startup:

ImageArrayFilename: /home/pkarasev3/source/kslice/source/data/remulak.mha
Creating first qVTK widget from parent centralWidget...Done!
Harvesting Tiberium...
new interactive labelmap with actors, max val = 1000
attempting to use Image Range: 0, 2202
ERROR: In /home/pkarasev3/source/vtk-5.6.1-src/IO/vtkMetaImageReader.cxx, line 84
vtkMetaImageReader (0x1fa1ee0): MetaImage cannot parse file.

ERROR: In /home/pkarasev3/source/vtk-5.6.1-src/IO/vtkMetaImageReader.cxx, line 224
vtkMetaImageReader (0x1fa1ee0): MetaImage cannot read data from file.

segmentor using ROI size: 7.90589
I think the # of rows is: 448, # of cols is: 448
num dims = 0; initialized KSegmentor3D with dims[0,1,2] = 448,448,30

- But this Crash is not 100% repeatable ... drawing a "donut" and pressing 's' when first
creating a label seems to do it though.